name: testing node
on:
  workflow_dispatch:
jobs:
    testing-node:
        runs-on: GitHub-Runner-1
        steps:
            - name: testing
              run: |
                node -v
                npm -v