name: Terraform Apply Dispatch
on:
  workflow_dispatch:

jobs:
    runing_test:
        runs-on: ubuntu-latest
        steps: 
            - name: check-docker-version
              run: |
                docker --version
            - name: get-sha
              run: |
                echo "the commit sha is ${{ github.sha }}"
            - name: see-env-variables
              run: |
                printenv
            - name: checkout-awscli-version
              run: |
                aws --version