name: Terraform Apply Dispatch
on:
  workflow_dispatch:

jobs:
    runing_test:
        runs-on: ubuntu-latest
        steps: 
            - name: check-docker-version
              run: |
                docker --version
            - name: get-sha
              run: |
                echo "the commit sha is ${{ github.sha }}"
            - name: see-env-variables
              run: |
                printenv
            - name: checkout-awscli-version
              run: |
                aws --version
            - name: check-terraform-version
              run: |
                terraform --version
            - name: checkout
              uses: actions/checkout@v2
              with:
                ref: testing
            - name: get-last-commit
              run: |
                git log -1
                echo "Last commit made by $(git log -1 --pretty=format:'%an <%ae>')"
              shell: bash